# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  react-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 12.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd react-app; yarn install
    - run: cd react-app; yarn build
    - run: cd react-app; yarn test
  fmt:
    runs-on: ubuntu-latest
    needs:
    - react-app
    strategy:
      matrix:
        python-version:
        - 3.7
        node-version:
        - 12.x
        fmt:
        - isort
        - unify
        - yapf
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -c py3.txt tox
    - name: Fmt
      run: tox -e py-${{ matrix.fmt }}
  lint:
    runs-on: ubuntu-latest
    needs:
    - fmt
    strategy:
      matrix:
        python-version:
        - 2.7
        - 3.7
        node-version:
        - 12.x
        lint:
        - flake8
        - pylint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -c py$(python -c 'import sys; print(sys.version_info.major)').txt tox
    - name: Lint
      run: |
        tox -e py-${{ matrix.lint }}
  test:
    runs-on: ubuntu-latest
    needs:
    - lint
    strategy:
      matrix:
        python-version:
        - 2.7
        - 3.7
        node-version:
        - 12.x
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -c py$(python -c 'import sys; print(sys.version_info.major)').txt tox
    - name: Test
      run: |
        tox -e py
